{"uuid": "cabe89ab-292c-438d-b5de-9180f709aeed", "children": ["57343385-2f52-4445-a60b-6a4414292816", "be61c4ab-8475-491e-927c-118f11670f95"], "befores": [{"name": "oneTimeSetUp", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EBACE49248>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\JASEEM-KHAN\\jenkins\\workspace\\Python\\tests\\conftest.py\", line 16, in oneTimeSetUp\n    driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', options=chrome_options)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 402, in _request\n    resp = http.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\request.py\", line 80, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\poolmanager.py\", line 330, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\connectionpool.py\", line 760, in urlopen\n    **response_kw\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\connectionpool.py\", line 760, in urlopen\n    **response_kw\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\connectionpool.py\", line 760, in urlopen\n    **response_kw\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\connectionpool.py\", line 720, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"c:\\users\\jaseem-khan\\jenkins\\shiningpanda\\jobs\\a7f5f354\\virtualenvs\\d41d8cd9\\lib\\site-packages\\urllib3\\util\\retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1586336389106, "stop": 1586336407177}], "start": 1586336389106, "stop": 1586336407959}